### PR TITLE
MVP #1

### PR DESCRIPTION
**Pull request by sesubash**
Added fade transition sample upon clicking on the slide links

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Hi @sesubash, 

I should've made it clearer, the point of this project is to implement a slideshow with no JavaScript. Thanks for your efforts though!

**Comment by sesubash** [comment]
@shakeelmohamed Updated with css only approach.

**Comment by shakeelmohamed** [comment]
@sesubash it works great! What can we do about the "flash" that happens when transitioning between slides?

**Comment by shakeelmohamed** [comment]
Closed in favor of #5

**Pull request closed without merging**
